[tool.uv.workspace]
members = ["backend/backend", "metrics-cli"]

[dependency-groups]
dev = [
    "black==25.9.0",
    "coverage>=7.10.6",
    "flake8==7.0.0",
    "mypy>=1.18.2",
    "pre-commit==4.3.0",
    "pytest==8.3.2",
    "pytest-cov==7.0.0",
]

[tool.black]
line-length = 100
